services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8088:8000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - backend

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - backend

networks:
  backend:
